<a href="https://colab.research.google.com/github/Yaroslav1121/MachineLearning/blob/main/%D0%9B%D0%A0_1_%D0%9A%D0%BB%D0%B8%D0%BC%D1%96%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 1
Виконати дії з матрицями
Варіант 12

In [2]:
# Завдання 1. Створіть одновимірний масив (вектор) із арифметичною прогресією, де кожне
# наступне число менше попереднього на 4, починаючи з 50, та виведіть його значення.
import numpy as np

# Параметри арифметичної прогресії
start = 50  # початкове значення
step = -4   # кожне наступне число менше на 4
length = 13 # кількість елементів (щоб отримати до 2)

# Створення масиву
array = np.arange(start, start + length * step, step)

# Виведення значень масиву
print(array)


[50 46 42 38 34 30 26 22 18 14 10  6  2]


In [3]:
# Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями суми
# добутків кожного числа на його попереднє, починаючи з 1, та виведіть його значення.
# Створення двовимірного масиву (матриці) 3x3

matrix = np.zeros((3, 3), dtype=int)

# Початкове число
num = 1

# Заповнюємо матрицю за правилом: сума добутків числа на його попереднє
for i in range(3):
    for j in range(3):
        if num == 1:
            matrix[i, j] = 1  # Перший елемент завжди 1
        else:
            matrix[i, j] = num * (num - 1)
        num += 1

# Виведення значень матриці
print(matrix)

[[ 1  2  6]
 [12 20 30]
 [42 56 72]]


In [5]:
# Завдання 3. Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні
# від -5 до 5 та знайдіть мінімальний елемент.
# Створення двовимірного масиву (матриці) 3x3 з випадковими числами в діапазоні від -5 до 5
matrix = np.random.randint(-5, 6, (3, 3))

# Виведення масиву
print("Масив:")
print(matrix)

# Знаходимо мінімальний елемент
min_element = np.min(matrix)

# Виведення мінімального елемента
print("Мінімальний елемент:", min_element)

Масив:
[[-4  0 -3]
 [-3 -5 -2]
 [-1  4 -1]]
Мінімальний елемент: -5


In [7]:
# Завдання 4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та обчисліть добуток елементів, що менше 0.2.
# Створення двовимірного масиву (матриці) 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
matrix = np.random.rand(3, 3)

# Виведення масиву
print("Масив:")
print(matrix)

# Знаходимо елементи, що менше 0.2
elements_less_than_0_2 = matrix[matrix < 0.2]

# Обчислюємо добуток елементів, що менше 0.2
product = np.prod(elements_less_than_0_2) if elements_less_than_0_2.size > 0 else 0

# Виведення результатів
print("Елементи, менше 0.2:", elements_less_than_0_2)
print("Добуток цих елементів:", product)

Масив:
[[0.77760515 0.56826807 0.07155924]
 [0.34227883 0.32399482 0.70788293]
 [0.14892621 0.65855048 0.66160223]]
Елементи, менше 0.2: [0.07155924 0.14892621]
Добуток цих елементів: 0.010657046926866188


In [8]:
# Завдання 5. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними
# числами від 0 до 1 та виконайте на них поелементні операції додавання, віднімання та множення.
# Створення двох одновимірних масивів розміром 4 з випадковими дійсними числами від 0 до 1
array1 = np.random.rand(4)
array2 = np.random.rand(4)

# Виведення масивів
print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)

# Поелементне додавання
addition = array1 + array2
print("\nПоелементне додавання:")
print(addition)

# Поелементне віднімання
subtraction = array1 - array2
print("\nПоелементне віднімання:")
print(subtraction)

# Поелементне множення
multiplication = array1 * array2
print("\nПоелементне множення:")
print(multiplication)

Масив 1:
[0.69439052 0.56892055 0.43394608 0.76758414]
Масив 2:
[0.48413313 0.40437898 0.28275206 0.88596115]

Поелементне додавання:
[1.17852364 0.97329953 0.71669814 1.65354529]

Поелементне віднімання:
[ 0.21025739  0.16454157  0.15119402 -0.11837701]

Поелементне множення:
[0.33617745 0.23005951 0.12269915 0.68004973]


In [9]:
# Завдання 6. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 5 до 10 та
# знайдіть їх добуток.
# Створення двох матриць 3x3 з випадковими цілими числами від 5 до 10
matrix1 = np.random.randint(5, 11, (3, 3))
matrix2 = np.random.randint(5, 11, (3, 3))

# Виведення матриць
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

# Обчислення добутку матриць
matrix_product = np.dot(matrix1, matrix2)

# Виведення результату
print("\nДобуток матриць:")
print(matrix_product)

Матриця 1:
[[ 8  9  7]
 [ 5  9  6]
 [10  6  7]]
Матриця 2:
[[10  9  8]
 [ 7 10  6]
 [ 6 10  8]]

Добуток матриць:
[[185 232 174]
 [149 195 142]
 [184 220 172]]


In [10]:
# Завдання 7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 5 та перемножте їх між собою.

# Створення матриці 2x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, (2, 3))

# Створення матриці 3x3 з випадковими цілими числами від 1 до 5
matrix2 = np.random.randint(1, 6, (3, 3))

# Виведення матриць
print("Матриця 1 (2x3):")
print(matrix1)
print("Матриця 2 (3x3):")
print(matrix2)

# Обчислення добутку матрицьj
matrix_product = np.dot(matrix1, matrix2)

# Виведення результату
print("\nДобуток матриць (2x3) * (3x3):")
print(matrix_product)

Матриця 1 (2x3):
[[1 3 1]
 [3 4 4]]
Матриця 2 (3x3):
[[4 1 3]
 [5 1 2]
 [1 1 3]]

Добуток матриць (2x3) * (3x3):
[[20  5 12]
 [36 11 29]]


In [12]:
# Завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 8 та знайдіть її обернену матрицю.

# Створення матриці 3x3 з випадковими цілими числами від 1 до 8
matrix = np.random.randint(1, 9, (3, 3))

# Виведення матрицці
print("Початкова матриця (3x3):")
print(matrix)

# Перевірка, чи є визначник матриці ненульовим
det = np.linalg.det(matrix)
if det != 0:
    # Обчислення оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nОбернена матриця не існує, оскільки визначник дорівнює 0.")

Початкова матриця (3x3):
[[4 1 4]
 [7 8 6]
 [4 4 1]]

Обернена матриця:
[[ 0.25396825 -0.23809524  0.41269841]
 [-0.26984127  0.19047619 -0.06349206]
 [ 0.06349206  0.19047619 -0.3968254 ]]


In [11]:
# Завдання 9. Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в
# діапазоні від 50 до 100 та транспонуйте її.

# Створення матриці 8x8 з випадковими дійсними числами від 50 до 100
matrix = np.random.uniform(50, 100, (8, 8))

# Виведення початкової матриці
print("Початкова матриця (8x8):")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)

Початкова матриця (8x8):
[[84.87445844 81.7303958  61.27566178 66.786016   93.97393963 87.51783725
  98.30374431 57.44939305]
 [63.20674479 55.37195303 84.20544151 70.30766041 83.15914161 51.97792163
  51.92633933 71.13111499]
 [96.59479294 66.71682262 62.55038775 86.09002606 55.86473102 53.45844619
  55.68388011 65.56767922]
 [78.7067834  89.31946326 55.25065433 88.80525621 87.18851915 75.79587098
  71.87033393 84.36645847]
 [92.44682387 90.03392487 90.89833438 86.05677301 54.9606425  84.89501345
  63.10021701 91.20617517]
 [78.41882413 50.71458166 63.49832168 65.73327482 58.56985419 94.45614723
  93.4534708  87.24921563]
 [79.40478295 83.9848157  93.53002483 80.84830321 85.24315205 79.45879311
  68.34230917 75.18331781]
 [62.55223825 87.81001184 66.26620345 82.94266202 79.36779551 89.50381164
  91.57465742 86.02516674]]

Транспонована матриця:
[[84.87445844 63.20674479 96.59479294 78.7067834  92.44682387 78.41882413
  79.40478295 62.55223825]
 [81.7303958  55.37195303 66.71682262 89.

In [13]:
# Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
# випадковими дійсними числами від -1 до 1, а вектор - випадковими цілими числами в
# діапазоні від -3 до 3 і знайдіть добуток матриці на вектор.

# Створення матриці 3x4 з випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, (3, 4))

# Створення вектора 4x1 з випадковими цілими числами від -3 до 3
vector = np.random.randint(-3, 4, (4, 1))

# Виведення початкової матриці та вектора
print("Матриця (3x4):")
print(matrix)

print("\nВектор (4x1):")
print(vector)

# Обчислення добутку матриці на вектор
matrix_vector_product = np.dot(matrix, vector)

# Виведення результату
print("\nДобуток матриці на вектор:")
print(matrix_vector_product)

Матриця (3x4):
[[-8.00186285e-01 -4.39520516e-01  1.43538582e-01  4.46025384e-01]
 [ 1.73653034e-01 -8.90684731e-01  7.99819453e-02  7.85180811e-02]
 [-6.73644514e-01  8.88675518e-04 -6.31087859e-01  5.31399491e-01]]

Вектор (4x1):
[[-3]
 [ 0]
 [-1]
 [ 1]]

Добуток матриці на вектор:
[[ 2.70304566]
 [-0.52242297]
 [ 3.18342089]]


In [14]:
# Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
# числами від 0 до 1, і знайдіть добуток матриці на вектор.

# Створення матриці 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (2, 3))

# Створення вектора 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, (3, 1))

# Виведення початкової матриці та вектора
print("Матриця (2x3):")
print(matrix)

print("\nВектор (3x1):")
print(vector)

# Обчислення добутку матриці на вектор
matrix_vector_product = np.dot(matrix, vector)

# Виведення результату
print("\nДобуток матриці на вектор:")
print(matrix_vector_product)

Матриця (2x3):
[[ 4  6  4]
 [ 2 10  2]]

Вектор (3x1):
[[0.3905687]
 [0.0717348]
 [0.653988 ]]

Добуток матриці на вектор:
[[4.60863557]
 [2.80646136]]


In [15]:
# Завдання 12. Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть відношення всіх елементів першої матриці до
# відповідних елементів другої матриці (поелементне ділення).

# Створення двох матриць 5x5 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, (5, 5))
matrix2 = np.random.randint(1, 11, (5, 5))

# Виведення початкових матриць
print("Матриця 1 (5x5):")
print(matrix1)

print("\nМатриця 2 (5x5):")
print(matrix2)

# Обчислення поелементного ділення
elementwise_division = matrix1 / matrix2

# Виведення результату
print("\nПоелементне ділення (матриця 1 / матриця 2):")
print(elementwise_division)

Матриця 1 (5x5):
[[8 4 7 9 6]
 [5 4 1 9 3]
 [2 1 2 7 4]
 [5 8 2 1 6]
 [3 9 8 3 1]]

Матриця 2 (5x5):
[[ 3  4  5  7  4]
 [ 5  7 10  8  2]
 [ 9  9  3  4  2]
 [ 8  5  1  5  4]
 [ 5  2  4  1  6]]

Поелементне ділення (матриця 1 / матриця 2):
[[2.66666667 1.         1.4        1.28571429 1.5       ]
 [1.         0.57142857 0.1        1.125      1.5       ]
 [0.22222222 0.11111111 0.66666667 1.75       2.        ]
 [0.625      1.6        2.         0.2        1.5       ]
 [0.6        4.5        2.         3.         0.16666667]]


In [16]:
# Завдання 13. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від -10 до 10 та знайдіть різницю їх елементів.

# Створення двох матриць 4x4 з випадковими цілими числами від -10 до 10
matrix1 = np.random.randint(-10, 11, (4, 4))
matrix2 = np.random.randint(-10, 11, (4, 4))

# Виведення початкових матриць
print("Матриця 1 (4x4):")
print(matrix1)

print("\nМатриця 2 (4x4):")
print(matrix2)

# Обчислення різниці матриць
difference = matrix1 - matrix2

# Виведення результату
print("\nРізниця матриць (матриця 1 - матриця 2):")
print(difference)

Матриця 1 (4x4):
[[ 8  9  4  1]
 [ 0  1 -6  8]
 [ 9  0  6 -5]
 [-9 -7 -2  7]]

Матриця 2 (4x4):
[[-10   1  10   6]
 [  9   1  -3  -8]
 [-10  -7   4   7]
 [ -3  -9  -3   1]]

Різниця матриць (матриця 1 - матриця 2):
[[ 18   8  -6  -5]
 [ -9   0  -3  16]
 [ 19   7   2 -12]
 [ -6   2   1   6]]


In [19]:
# Завдання 14. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть суму елементів матриці, які менше за їх середнє арифметичне значення.

# Створення матриці 3x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Виведення початкової матриці
print("Матриця (3x3):")
print(matrix)

# Обчислення середнього арифметичного значення
mean_value = np.mean(matrix)
print("\nСереднє арифметичне значення:", mean_value)

# Знаходження суми елементів, які менше за середнє арифметичне
sum_below_mean = np.sum(matrix[matrix < mean_value])

# Виведення результату
print("\nСума елементів, які менше за середнє арифметичне:", sum_below_mean)

Матриця (3x3):
[[ 5  8  6]
 [ 6  6 10]
 [ 8  1  4]]

Середнє арифметичне значення: 6.0

Сума елементів, які менше за середнє арифметичне: 10


In [20]:
# Завдання 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє гармонічне
# значення елементів кожного рядка матриці.

# Створення матриці 3x3 з випадковими дійсними числами від -2 до 2
matrix = np.random.uniform(-2, 2, (3, 3))

# Виведення початкової матриці
print("Матриця (3x3):")
print(matrix)

# Обчислення середнього гармонічного значення для кожного рядка
harmonic_mean = np.zeros(matrix.shape[0])  # Вектор для зберігання результатів

for i in range(matrix.shape[0]):
    # Обчислення середнього гармонічного значення
    harmonic_mean[i] = len(matrix[i]) / np.sum(1 / matrix[i])

# Перетворення вектору в стовпчик
harmonic_mean_vector = harmonic_mean.reshape(-1, 1)

# Виведення результату
print("\nВектор-стовпчик з середнім гармонічним значенням:")
print(harmonic_mean_vector)

Матриця (3x3):
[[-0.11574434 -1.11948463  0.30234583]
 [-1.84846873  1.45542024  1.39256477]
 [ 0.59971048 -1.45735655  0.75357605]]

Вектор-стовпчик з середнім гармонічним значенням:
[[-0.4818868 ]
 [ 3.47142708]
 [ 1.2996558 ]]


In [ ]:
# Отже за допомогою цієї лабораторної роботи ми навчилися\повторили роботи з матрицями, векторами, масивами та ін.
# а також провели роботу з різними математичними операціями з даними елементами.